
# cargo-vet config file

[cargo-vet]
version = "0.6"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.chromeos]
url = "https://chromium.googlesource.com/chromiumos/third_party/rust_crates/+/main/cargo-vet/audits.toml?format=TEXT"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[[exemptions.addr2line]]
version = "0.17.0"
criteria = "safe-to-deploy"

[[exemptions.adler]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.aead]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.aes]]
version = "0.7.5"
criteria = "safe-to-deploy"

[[exemptions.ahash]]
version = "0.7.6"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "0.7.18"
criteria = "safe-to-deploy"

[[exemptions.backtrace]]
version = "0.3.67"
criteria = "safe-to-deploy"

[[exemptions.base64ct]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.bech32]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.bellman]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.bip0039]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bitvec]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.blake2b_simd]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.blake2s_simd]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.block-modes]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.block-padding]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.bls12_381]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.bs58]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.byte-slice-cast]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.byteorder]]
version = "1.4.3"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.0.79"
criteria = "safe-to-deploy"

[[exemptions.chacha20]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.chacha20poly1305]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.cipher]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.clearscreen]]
version = "1.0.9"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-channel]]
version = "0.5.6"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-deque]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-epoch]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.8"
criteria = "safe-to-deploy"

[[exemptions.crypto-mac]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek]]
version = "3.2.0"
criteria = "safe-to-deploy"

[[exemptions.cxx]]
version = "1.0.68"
criteria = "safe-to-deploy"

[[exemptions.cxxbridge-flags]]
version = "1.0.68"
criteria = "safe-to-deploy"

[[exemptions.cxxbridge-macro]]
version = "1.0.68"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.directories]]
version = "4.0.1"
criteria = "safe-to-deploy"

[[exemptions.dirs]]
version = "2.0.2"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys]]
version = "0.3.7"
criteria = "safe-to-deploy"

[[exemptions.ed25519-zebra]]
version = "3.0.0"
criteria = "safe-to-deploy"

[[exemptions.ff]]
version = "0.12.0"
criteria = "safe-to-deploy"

[[exemptions.fixed-hash]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.fpe]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.funty]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.futures-channel]]
version = "0.3.21"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.21"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.21"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.27"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.6"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.6"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.27.0"
criteria = "safe-to-deploy"

[[exemptions.group]]
version = "0.12.0"
criteria = "safe-to-deploy"

[[exemptions.gumdrop]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.gumdrop_derive]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.hdwallet]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.2.6"
criteria = "safe-to-deploy"

[[exemptions.hmac]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.http-body]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.httparse]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.httpdate]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.hyper]]
version = "0.14.25"
criteria = "safe-to-deploy"

[[exemptions.impl-codec]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.impl-trait-for-tuples]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.incrementalmerkletree]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "1.8.1"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.60"
criteria = "safe-to-deploy"

[[exemptions.jubjub]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.140"
criteria = "safe-to-deploy"

[[exemptions.libm]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.link-cplusplus]]
version = "1.0.6"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.7"
criteria = "safe-to-deploy"

[[exemptions.mach]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.matchers]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.memoffset]]
version = "0.6.5"
criteria = "safe-to-deploy"

[[exemptions.memuse]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.metrics]]
version = "0.19.0"
criteria = "safe-to-deploy"

[[exemptions.metrics-exporter-prometheus]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.metrics-macros]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.metrics-util]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.5.3"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.nix]]
version = "0.26.1"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "5.1.2"
criteria = "safe-to-deploy"

[[exemptions.nonempty]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.nu-ansi-term]]
version = "0.46.0"
criteria = "safe-to-deploy"

[[exemptions.num_cpus]]
version = "1.13.1"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.30.1"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.17.0"
criteria = "safe-to-deploy"

[[exemptions.overload]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.pairing]]
version = "0.22.0"
criteria = "safe-to-deploy"

[[exemptions.parity-scale-codec]]
version = "3.2.1"
criteria = "safe-to-deploy"

[[exemptions.parity-scale-codec-derive]]
version = "3.1.3"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.11.2"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.password-hash]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.pasta_curves]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.pbkdf2]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.phf]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.phf_codegen]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.phf_generator]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.phf_shared]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.pin-utils]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.poly1305]]
version = "0.7.2"
criteria = "safe-to-deploy"

[[exemptions.portable-atomic]]
version = "0.3.19"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.primitive-types]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-crate]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.quanta]]
version = "0.9.3"
criteria = "safe-to-deploy"

[[exemptions.radium]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.raw-cpuid]]
version = "10.6.0"
criteria = "safe-to-deploy"

[[exemptions.reddsa]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.redjubjub]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.redox_users]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.1.10"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.6.27"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.16.20"
criteria = "safe-to-deploy"

[[exemptions.ripemd]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.rustc-hex]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.11"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.secp256k1]]
version = "0.21.3"
criteria = "safe-to-deploy"

[[exemptions.secp256k1-sys]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.secrecy]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.136"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.136"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.81"
criteria = "safe-to-deploy"

[[exemptions.sha2]]
version = "0.9.9"
criteria = "safe-to-deploy"

[[exemptions.sharded-slab]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.siphasher]]
version = "0.3.10"
criteria = "safe-to-deploy"

[[exemptions.sketches-ddsketch]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.10.0"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.static_assertions]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.subtle]]
version = "2.4.1"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.102"
criteria = "safe-to-deploy"

[[exemptions.tap]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.terminfo]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "1.0.30"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "1.0.30"
criteria = "safe-to-deploy"

[[exemptions.thread_local]]
version = "1.1.4"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.20"
criteria = "safe-to-deploy"

[[exemptions.time-core]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.time-macros]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.26.0"
criteria = "safe-to-deploy"

[[exemptions.toml_edit]]
version = "0.19.7"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.37"
criteria = "safe-to-deploy"

[[exemptions.tracing-appender]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.23"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.30"
criteria = "safe-to-deploy"

[[exemptions.tracing-subscriber]]
version = "0.3.16"
criteria = "safe-to-deploy"

[[exemptions.try-lock]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.uint]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.unicode-xid]]
version = "0.2.4"
criteria = "safe-to-deploy"

[[exemptions.valuable]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.want]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.10.2+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.84"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.84"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.84"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.84"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.61"
criteria = "safe-to-deploy"

[[exemptions.which]]
version = "4.3.0"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winnow]]
version = "0.3.6"
criteria = "safe-to-deploy"

[[exemptions.wyz]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.4.3"
criteria = "safe-to-deploy"

[[exemptions.zeroize_derive]]
version = "1.3.2"
criteria = "safe-to-deploy"
