os: osx
addons:
  homebrew:
    packages:
      - git
      - pkgconfig
      - automake
      - autoconf
      - libtool
      - coreutils
install:
  - sudo easy_install pip
  - sudo pip install pyblake2 pyzmq
  - g++ --version
  - gcc --version
script:
  - ./zcutil/build.sh -j$(nproc)
