[package]
name = "librustzcash"
description = "Rust FFI used by the zcashd binary. Not an official API."
version = "0.2.0"
authors = [
    "Sean Bowe <sean@electriccoin.co>",
    "Jay Graber",
    "Jack Grigg <jack@electriccoin.co>",
    "Daira Hopwood <daira@electriccoin.co>",
    "Ying Tong Lai <yingtong@electriccoin.co>",
    "Simon Liu",
    "Kris Nuttycombe <kris@electriccoin.co>",
    "Larry Ruane <larry@electriccoin.co>",
    "Steven Smith <steven@electriccoin.co>"
]
homepage = "https://github.com/zcash/zcash"
repository = "https://github.com/zcash/zcash"
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2018"
rust-version = "1.59"

[lib]
name = "rustzcash"
path = "src/rust/src/rustzcash.rs"
crate-type = ["staticlib"]

[[bin]]
name = "zcashd-wallet-tool"
path = "src/rust/bin/wallet_tool.rs"

[dependencies]
bellman = "0.13"
blake2b_simd = "1"
blake2s_simd = "1"
bls12_381 = "0.7"
byteorder = "1"
group = "0.12"
incrementalmerkletree = "0.3"
libc = "0.2"
jubjub = "0.9"
memuse = "0.2"
nonempty = "0.7"
orchard = "0.1"
secp256k1 = "0.21"
subtle = "2.2"
rand_core = "0.6"
tracing = "0.1"
tracing-core = "0.1"
tracing-appender = "0.2"
zcash_address = "0.1"
zcash_encoding = "0.1"
zcash_history = "0.3"
zcash_note_encryption = "0.1"
zcash_primitives = { version = "0.6", features = ["transparent-inputs"] }
zcash_proofs = "0.6"
ed25519-zebra = "3"
zeroize = "1.4.2"

# Metrics
ipnet = "2"
metrics = "0.17"
metrics-exporter-prometheus = "0.6"

# Wallet tool
# (also depends on tracing, and tracing-subscriber with "env-filter" and "fmt" features)
anyhow = "1.0"
backtrace = "0.3"
clearscreen = "1.0"
gumdrop = "0.8"
rand = "0.8"
secrecy = "0.8"
thiserror = "1"
time = { version = "0.3", features = ["formatting", "macros"] }

[dependencies.tracing-subscriber]
version = "0.3"
default-features = false
features = ["ansi", "env-filter", "fmt", "time"]

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1
