# FIXME: This is hardcoded to linux-gnu binaries.
version = "1.44.1"
urlbase = "https://static.rust-lang.org/dist/"
archive = "rust-1.44.1-x86_64-unknown-linux-gnu.tar.gz"
sha256 = "a41df89a461a580536aeb42755e43037556fba2e527dd13a1e1bb0749de28202"
buildscript = true
nativeBuildInputs = [ "file" ]
