name: Komodo Linux CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 0 * * 1'

jobs:

  linux-build:
    name: Linux Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install deps (Linux)

        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update  # prevents repo404 errors on apt-remove below
          sudo apt-get remove php* msodbcsql17 mysql* powershell dotn*
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get upgrade -y
          sudo apt-get install -q \
                 curl \
                 python3 \
                 python3-dev \
                 python3-setuptools \
                 python3-pip \
                 libcurl4-openssl-dev \
                 libssl-dev -y
          python3 -m pip install setuptools wheel
          python3 -m pip install slick-bitcoinrpc pytest wget jsonschema
          ./zcutil/fetch-params.sh
      - name: Build (Linux)
        run: |
          # flag for some CC tests transactions - so DO NOT USE THIS CI ARTIFACTS IN PRODUCTION!!!
          CONFIGURE_FLAGS='CPPFLAGS=-DTESTMODE' ./zcutil/build.sh -j$(nproc)
          tar -czvf komodo-linux.tar.gz src/komodod src/komodo-cli
      - name: Upload komodo-linux.tar.gz as artifact
        uses: actions/upload-artifact@v1
        with:
          name: komodo-linux
          path: ./komodo-linux.tar.gz

  linux-test-dice-token-reards-faucet-cc:

    name: Test (Linux/Dice, Token, Faucet, Rewards)
    runs-on: ubuntu-latest
    needs: linux-build

    steps:
      - uses: actions/checkout@v2

      - name: Install deps (Dice, Token, Faucet, Rewards CC)
        run: |
          sudo apt-get update
          sudo apt-get install -q \
                 curl \
                 python3 \
                 python3-dev \
                 python3-setuptools \
                 python3-pip \
                 libcurl4-openssl-dev \
                 libssl-dev -y
          python3 -m pip install setuptools wheel
          python3 -m pip install pytest wget jsonschema
          python3 -m pip install -Iv https://github.com/KomodoPlatform/slick-bitcoinrpc/archive/refs/tags/0.1.4.tar.gz
      - name: Download komodo-linux.tar.gz
        uses: actions/download-artifact@v1
        with:
          name: komodo-linux

      - name: Test CC (Linux)
        run: |
          mv komodo-linux/komodo-linux.tar.gz .
          mkdir -p src
          tar xzvf komodo-linux.tar.gz
          ./zcutil/fetch-params.sh
          cd qa/pytest_komodo
          ./ci_setup.sh "cc_modules/test_dice.py cc_modules/test_faucet.py cc_modules/test_token.py cc_modules/test_rewards.py"
  linux-test-oracles:

    name: Test (Linux/OraclesCC)
    runs-on: ubuntu-latest
    needs: linux-build

    steps:
      - uses: actions/checkout@v2

      - name: Install deps (OraclesCC)
        run: |
          sudo apt-get update
          sudo apt-get install -q \
                 curl \
                 python3 \
                 python3-dev \
                 python3-setuptools \
                 python3-pip \
                 libcurl4-openssl-dev \
                 libssl-dev -y
          python3 -m pip install setuptools wheel
          python3 -m pip install slick-bitcoinrpc pytest wget jsonschema
      - name: Download komodo-linux.tar.gz
        uses: actions/download-artifact@v1
        with:
          name: komodo-linux

      - name: Oracles Test (Linux)
        run: |
          mv komodo-linux/komodo-linux.tar.gz .
          mkdir -p src
          tar xzvf komodo-linux.tar.gz
          ./zcutil/fetch-params.sh
          cd qa/pytest_komodo
          ./ci_setup.sh cc_modules/test_oracles.py
  linux-test-baserpc:

    name: Test (Linux/BasicRPC)
    runs-on: ubuntu-latest
    needs: linux-build

    steps:
      - uses: actions/checkout@v2

      - name: Install deps (BasicRPC)
        run: |
          sudo apt-get update
          sudo apt-get install -q \
                 curl \
                 python3 \
                 python3-dev \
                 python3-setuptools \
                 python3-pip \
                 libcurl4-openssl-dev \
                 libssl-dev -y
          python3 -m pip install setuptools wheel
          python3 -m pip install slick-bitcoinrpc pytest wget jsonschema
      - name: Download komodo-linux.tar.gz
        uses: actions/download-artifact@v1
        with:
          name: komodo-linux

      - name: BasicRPC Test (Linux)
        run: |
          mv komodo-linux/komodo-linux.tar.gz .
          mkdir -p src
          tar xzvf komodo-linux.tar.gz
          ./zcutil/fetch-params.sh
          cd qa/pytest_komodo
          ./ci_setup.sh basic
  linux-test-channels:

    name: Test (Linux/ChannelsCC)
    runs-on: ubuntu-latest
    needs: linux-build

    steps:
      - uses: actions/checkout@v2

      - name: Install deps (ChannelsCC)
        run: |
          sudo apt-get update
          sudo apt-get install -q \
                 curl \
                 python3 \
                 python3-dev \
                 python3-setuptools \
                 python3-pip \
                 libcurl4-openssl-dev \
                 libssl-dev -y
          python3 -m pip install setuptools wheel
          python3 -m pip install slick-bitcoinrpc pytest wget jsonschema
      - name: Download komodo-linux.tar.gz
        uses: actions/download-artifact@v1
        with:
          name: komodo-linux

      - name: Channels Test (Linux)
        run: |
          mv komodo-linux/komodo-linux.tar.gz .
          mkdir -p src
          tar xzvf komodo-linux.tar.gz
          ./zcutil/fetch-params.sh
          cd qa/pytest_komodo
          ./ci_setup.sh cc_modules/test_channels.py
  linux-test-heir:

    name: Test (Linux/HeirCC)
    runs-on: ubuntu-latest
    needs: linux-build

    steps:
      - uses: actions/checkout@v2

      - name: Install deps (HeirCC)
        run: |
          sudo apt-get update
          sudo apt-get install -q \
                 curl \
                 python3 \
                 python3-dev \
                 python3-setuptools \
                 python3-pip \
                 libcurl4-openssl-dev \
                 libssl-dev -y
          python3 -m pip install setuptools wheel
          python3 -m pip install slick-bitcoinrpc pytest wget jsonschema
      - name: Download komodo-linux.tar.gz
        uses: actions/download-artifact@v1
        with:
          name: komodo-linux

      - name: Heir Test (Linux)
        run: |
          mv komodo-linux/komodo-linux.tar.gz .
          mkdir -p src
          tar xzvf komodo-linux.tar.gz
          ./zcutil/fetch-params.sh
          cd qa/pytest_komodo
          ./ci_setup.sh cc_modules/test_heir.py
