name: Komodo CI

on: [push, pull_request]

jobs:
  linux-build:
    name: Linux Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1

      - name: Install deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get remove php7.1-fpm php7.2-fpm php7.3-fpm php7.3-common
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get update
          sudo apt-get install -q \
                 curl \
                 python3 \
                 python3-dev \
                 python3-setuptools \
                 python3-pip \
                 libcurl4-openssl-dev \
                 libssl-dev -y
          python3 -m pip install setuptools wheel
          python3 -m pip install slick-bitcoinrpc pytest wget jsonschema
          ./zcutil/fetch-params.sh
      
      - name: Build (Linux)
        if: runner.os == 'Linux'
        run: |
          # flag for some CC tests transactions - so DO NOT USE THIS CI ARTIFACTS IN PRODUCTION!!!
          CONFIGURE_FLAGS='CPPFLAGS=-DTESTMODE' ./zcutil/build.sh -j$(nproc)
          tar -czvf komodo-linux.tar.gz src/komodod src/komodo-cli

      - name: Upload komodo-linux.tar.gz as artifact
        uses: actions/upload-artifact@v1
        with:
          name: komodo-linux
          path: ./komodo-linux.tar.gz
#       - name: Install deps (macOS)
#         if: runner.os == 'macOS'
#         run: |
#           brew update
#           brew upgrade
#           brew tap discoteq/discoteq; brew install flock
#           brew install autoconf autogen automake
#           brew install gcc@8
#           brew install binutils
#           brew install protobuf
#           brew install coreutils
#           brew install wget
#           brew install python3
#           pip3 install setuptools wheel slick-bitcoinrpc pytest wget
#           ./zcutil/fetch-params.sh
        
#       - name: Build (macOS)
#         if: runner.os == 'macOS'
#         run: |
#           # flag for some CC tests transactions - so DO NOT USE THIS CI ARTIFACTS IN PRODUCTION!!!
#           export CPATH=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/
#           CONFIGURE_FLAGS='CPPFLAGS=-DTESTMODE' ./zcutil/build-mac.sh -j4
#       - name: Run CC tests
#         if: runner.os == 'Linux' || runner.os == 'macOS'


  linux-test-dice-token-reards-faucet-cc:
    name: Test (Linux/Dice, Token, Faucet, Rewards)
    runs-on: ubuntu-latest
    needs: linux-build

    steps:
      - uses: actions/checkout@v1

      - name: Install deps (Dice, Token, Faucet, Rewards CC)
        run: |
          sudo apt-get update
          sudo apt-get install -q \
                 curl \
                 python3 \
                 python3-dev \
                 python3-setuptools \
                 python3-pip \
                 libcurl4-openssl-dev \
                 libssl-dev -y
          python3 -m pip install setuptools wheel
          python3 -m pip install slick-bitcoinrpc pytest wget jsonschema

      - name: Download komodo-linux.tar.gz
        uses: actions/download-artifact@v1
        with:
          name: komodo-linux

      - name: Test CC (Linux)
        run: |
          mv komodo-linux/komodo-linux.tar.gz .
          mkdir -p src
          tar xzvf komodo-linux.tar.gz
          ./zcutil/fetch-params.sh
          cd qa/pytest_komodo
          ./ci_setup.sh "cc_modules/test_dice.py cc_modules/test_faucet.py cc_modules/test_token.py cc_modules/test_rewards.py"

  linux-test-oracles:
    name: Test (Linux/OraclesCC)
    runs-on: ubuntu-latest
    needs: linux-build

    steps:
      - uses: actions/checkout@v1

      - name: Install deps (OraclesCC)
        run: |
          sudo apt-get update
          sudo apt-get install -q \
                 curl \
                 python3 \
                 python3-dev \
                 python3-setuptools \
                 python3-pip \
                 libcurl4-openssl-dev \
                 libssl-dev -y
          python3 -m pip install setuptools wheel
          python3 -m pip install slick-bitcoinrpc pytest wget jsonschema

      - name: Download komodo-linux.tar.gz
        uses: actions/download-artifact@v1
        with:
          name: komodo-linux

      - name: Oracles Test (Linux)
        run: |
          mv komodo-linux/komodo-linux.tar.gz .
          mkdir -p src
          tar xzvf komodo-linux.tar.gz
          ./zcutil/fetch-params.sh
          cd qa/pytest_komodo
          ./ci_setup.sh cc_modules/test_oracles.py

  linux-test-baserpc:
    name: Test (Linux/BasicRPC)
    runs-on: ubuntu-latest
    needs: linux-build

    steps:
      - uses: actions/checkout@v1

      - name: Install deps (BasicRPC)
        run: |
          sudo apt-get update
          sudo apt-get install -q \
                 curl \
                 python3 \
                 python3-dev \
                 python3-setuptools \
                 python3-pip \
                 libcurl4-openssl-dev \
                 libssl-dev -y
          python3 -m pip install setuptools wheel
          python3 -m pip install slick-bitcoinrpc pytest wget jsonschema

      - name: Download komodo-linux.tar.gz
        uses: actions/download-artifact@v1
        with:
          name: komodo-linux

      - name: BasicRPC Test (Linux)
        run: |
          mv komodo-linux/komodo-linux.tar.gz .
          mkdir -p src
          tar xzvf komodo-linux.tar.gz
          ./zcutil/fetch-params.sh
          cd qa/pytest_komodo
          ./ci_setup.sh basic

  linux-test-channels:
    name: Test (Linux/ChannelsCC)
    runs-on: ubuntu-latest
    needs: linux-build

    steps:
      - uses: actions/checkout@v1

      - name: Install deps (ChannelsCC)
        run: |
          sudo apt-get update
          sudo apt-get install -q \
                 curl \
                 python3 \
                 python3-dev \
                 python3-setuptools \
                 python3-pip \
                 libcurl4-openssl-dev \
                 libssl-dev -y
          python3 -m pip install setuptools wheel
          python3 -m pip install slick-bitcoinrpc pytest wget jsonschema

      - name: Download komodo-linux.tar.gz
        uses: actions/download-artifact@v1
        with:
          name: komodo-linux

      - name: Channels Test (Linux)
        run: |
          mv komodo-linux/komodo-linux.tar.gz .
          mkdir -p src
          tar xzvf komodo-linux.tar.gz
          ./zcutil/fetch-params.sh
          cd qa/pytest_komodo
          ./ci_setup.sh cc_modules/test_channels.py

  linux-test-heir:
    name: Test (Linux/HeirCC)
    runs-on: ubuntu-latest
    needs: linux-build

    steps:
      - uses: actions/checkout@v1

      - name: Install deps (HeirCC)
        run: |
          sudo apt-get update
          sudo apt-get install -q \
                 curl \
                 python3 \
                 python3-dev \
                 python3-setuptools \
                 python3-pip \
                 libcurl4-openssl-dev \
                 libssl-dev -y
          python3 -m pip install setuptools wheel
          python3 -m pip install slick-bitcoinrpc pytest wget jsonschema

      - name: Download komodo-linux.tar.gz
        uses: actions/download-artifact@v1
        with:
          name: komodo-linux

      - name: Heir Test (Linux)
        run: |
          mv komodo-linux/komodo-linux.tar.gz .
          mkdir -p src
          tar xzvf komodo-linux.tar.gz
          ./zcutil/fetch-params.sh
          cd qa/pytest_komodo
          ./ci_setup.sh cc_modules/test_heir.py

  windows-build:

    name: Win Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Win on Unix
      env:
        DEBIAN_FRONTEND: noninteractive
      if: runner.os == 'Linux'
      run: |
        sudo apt-get remove php5.6-fpm php7.0-fpm php7.1-fpm php7.2-fpm php7.3-fpm php7.3-common
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install build-essential pkg-config libc6-dev m4 g++-multilib autoconf libtool libncurses-dev unzip git python zlib1g-dev wget bsdmainutils automake libboost-all-dev libssl-dev libprotobuf-dev protobuf-compiler libqrencode-dev libdb++-dev ntp ntpdate nano software-properties-common curl libevent-dev libcurl4-gnutls-dev cmake clang libsodium-dev -y
        sudo apt-get install build-essential pkg-config libc6-dev m4 g++-multilib autoconf libtool ncurses-dev unzip git python python-zmq zlib1g-dev wget libcurl4-gnutls-dev bsdmainutils automake curl cmake mingw-w64
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        source $HOME/.cargo/env
        rustup target add x86_64-pc-windows-gnu
        sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
        sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
        CONFIGURE_FLAGS='CPPFLAGS=-DTESTMODE' ./zcutil/build-win.sh -j$(nproc)
        zip --junk-paths komodod_win src/komodod.exe
    - name: Upload komodod.exe as artifact
      uses: actions/upload-artifact@v1
      with:
        name: komodod_win
        path: ./komodod_win.zip
